# Stage 1: Build stage
FROM fedora:42 AS builder

# Install build dependencies
RUN dnf install -y git npm
RUN  dnf -y update

RUN git clone --depth 1 https://github.com/carloszamora08/Proyecto-final-CPYD.git /root/tournaments

# Set working directory for build
WORKDIR /root/tournaments/tournament_frontend

RUN npm install

# Expose the application port
EXPOSE 5173

# Start your application
CMD ["npm", "run", "dev"]